Add print_dictionary helper
oracle-samples/drgn-tools pull request #2
Opened 2023-10-18 10:19 UTC by Hannibal404

2023-10-18 10:29 UTC, Hannibal404 commented
Made the organization membership public

2023-10-19 00:15 UTC, brenns10 requested changes
One small nit but otherwise, it looks good to me!

2023-10-19 00:15 UTC, brenns10 commented on drgn_tools/table.py
> +            f"{title.ljust(lcol_length)}: {dictionary[title]:<}",
`{dictionary[title]:<}`
nit: technically, left alignment is the default, so there's no need to specify it

2023-10-19 07:04 UTC, brenns10 approved these changes

2023-10-19 07:04 UTC, merged

2023-10-19 07:05 UTC, brenns10 commented
Thanks for the quick work unblocking both pull requests!