Add virtutil module, check platform type and cpu hp state
oracle-samples/drgn-tools pull request #70
Opened 2024-02-06 11:46 UTC by pssatapathy-oracle

2024-02-20 23:42 UTC, brenns10 requested changes

2024-02-23 05:13 UTC, pssatapathy-oracle commented on drgn_tools/virtutil.py
> +    return "BareMetal"
Ok Agree

2024-02-23 05:14 UTC, pssatapathy-oracle commented on drgn_tools/virtutil.py
> +    return str_hyper_type
Ok Better way to do it

2024-02-23 05:14 UTC, pssatapathy-oracle commented on drgn_tools/virtutil.py
> +def get_cpuhp_state(prog, cpu: int) -> str:
Ack

2024-02-23 05:25 UTC, pssatapathy-oracle commented on drgn_tools/virtutil.py
> +        print(cpu_state_str)
Ack

2024-02-23 05:25 UTC, pssatapathy-oracle commented on drgn_tools/virtutil.py
> +    """Display the kernel command line"""
Ack

2024-02-23 05:26 UTC, pssatapathy-oracle commented on drgn_tools/virtutil.py
> +# Copyright (c) 2024, Oracle and/or its affiliates.
I used the word virtutil as I am planning to use this module as lib

2024-03-19 22:28 UTC, brenns10 requested changes
Just a few tweaks for consistency, but as discussed I will merge this once these changes are made. I know you're working on more virtutil features for a later PR.

2024-03-19 22:28 UTC, brenns10 commented on drgn_tools/virtutil.py
> +        return
In addition to printing the information in the "sys" module, let's print `show_platform(prog)` and `show_cpuhp_state(prog)` here, if nothing else.

2024-03-19 22:28 UTC, brenns10 commented on drgn_tools/virtutil.py
> +    """"""
This still should contain _something_, maybe "Displays guest-side virtualization information"?

2024-03-19 22:28 UTC, brenns10 commented on drgn_tools/virtutil.py
> +def show_platform(prog: Program) -> str:
If this now returns a string rather than printing it, it should be named `get_platform()` rather than `show_platform()`.

2024-03-29 17:17 UTC, brenns10 approved these changes

2024-03-29 17:17 UTC, merged